In [2]:
from keras.layers import Dense, Dropout, LSTM, Embedding, Conv1D, MaxPooling1D
from keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential
import pandas as pd
import numpy as np

C:\Users\yichu\Anaconda3\envs\tensorflow\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [3]:
input = pd.read_csv('./data_5.txt',sep=",", header=None, dtype="float").values
print(input.shape)

(62343, 80)


In [4]:
def load_data(test_split = 0.2):
    print ('Loading data...')
    input = pd.read_csv('./data_5.txt',sep=",", header=None, dtype="float").values
    x_shape = input.shape[0]
    y_shape = input.shape[1]
    
    boundary = (int)(x_shape * 0.7)
    X_train = input[0: boundary, 0:y_shape - 1]
    y_train = input[0: boundary, -1]
    X_test = input[boundary:x_shape, 0:y_shape - 1]
    y_test = input[boundary:x_shape, -1]

    print("Data is loaded")
    return pad_sequences(X_train), y_train, pad_sequences(X_test), y_test

In [5]:
X_train, y_train, X_test, y_test = load_data()

Loading data...
Data is loaded


In [43]:
def create_model(input_shape):
    print ('Creating model...')
    model = Sequential()
    model.add(LSTM(activation="sigmoid", return_sequences=True, units=128, recurrent_activation="tanh", input_dim=79))          
    #model.add(Dropout(0.5))
    #model.add(LSTM(activation="sigmoid", units=256, recurrent_activation="hard_sigmoid", return_sequences=True))
    #model.add(Dropout(0.5))
    model.add(Dense(1, activation='sigmoid'))

    print ('Compiling...')
    model.compile(loss='mean_squared_error',
                  optimizer='adam',
                  metrics=['accuracy'])
    return model

In [35]:
y_train.shape

(43640,)

In [36]:
seq_len = 100
X_train_seq = X_train[:(X_train.shape[0] - X_train.shape[0] % seq_len),:]
shp = X_train_seq.shape
X_train_seq = np.reshape(X_train_seq, [shp[0]//seq_len, seq_len, shp[1]])
X_train_seq.shape

y_train_seq = y_train[:(X_train.shape[0] - X_train.shape[0] % seq_len)]
y_train_seq = np.reshape(y_train_seq, [shp[0]//seq_len, seq_len, 1])


In [45]:
model = create_model(X_train.shape)

print ('Fitting model...')
hist = model.fit(X_train_seq, y_train_seq, batch_size=48, epochs=100, validation_split = 0.1, verbose = 1)

Creating model...


C:\Users\yichu\Anaconda3\envs\tensorflow\lib\site-packages\ipykernel_launcher.py:4: UserWarning: The `input_dim` and `input_length` arguments in recurrent layers are deprecated. Use `input_shape` instead.
  after removing the cwd from sys.path.
C:\Users\yichu\Anaconda3\envs\tensorflow\lib\site-packages\ipykernel_launcher.py:4: UserWarning: Update your `LSTM` call to the Keras 2 API: `LSTM(activation="sigmoid", return_sequences=True, units=128, recurrent_activation="tanh", input_shape=(None, 79))`
  after removing the cwd from sys.path.


Compiling...
Fitting model...
Train on 392 samples, validate on 44 samples
Epoch 1/100
392/392 [==============================] - 2s 5ms/step - loss: 0.1527 - acc: 0.7642 - val_loss: 0.0469 - val_acc: 0.9477
Epoch 2/100
392/392 [==============================] - 1s 2ms/step - loss: 0.0490 - acc: 0.9372 - val_loss: 0.0417 - val_acc: 0.9480
Epoch 3/100
392/392 [==============================] - 1s 2ms/step - loss: 0.0438 - acc: 0.9386 - val_loss: 0.0358 - val_acc: 0.9489
Epoch 4/100
392/392 [==============================] - 1s 2ms/step - loss: 0.0378 - acc: 0.9459 - val_loss: 0.0304 - val_acc: 0.9555
Epoch 5/100
392/392 [==============================] - 1s 2ms/step - loss: 0.0354 - acc: 0.9516 - val_loss: 0.0283 - val_acc: 0.9600
Epoch 6/100
392/392 [==============================] - 1s 2ms/step - loss: 0.0334 - acc: 0.9548 - val_loss: 0.0271 - val_acc: 0.9595
Epoch 7/100
392/392 [==============================] - 1s 2ms/step - loss: 0.0311 - acc: 0.9572 - val_loss: 0.0253 - val_acc: 0

392/392 [==============================] - 1s 2ms/step - loss: 0.0035 - acc: 0.9964 - val_loss: 0.0093 - val_acc: 0.9895
Epoch 62/100
392/392 [==============================] - 1s 2ms/step - loss: 0.0032 - acc: 0.9969 - val_loss: 0.0098 - val_acc: 0.9884
Epoch 63/100
392/392 [==============================] - 1s 2ms/step - loss: 0.0030 - acc: 0.9972 - val_loss: 0.0094 - val_acc: 0.9889
Epoch 64/100
392/392 [==============================] - 1s 2ms/step - loss: 0.0029 - acc: 0.9973 - val_loss: 0.0093 - val_acc: 0.9891
Epoch 65/100
392/392 [==============================] - 1s 2ms/step - loss: 0.0028 - acc: 0.9973 - val_loss: 0.0091 - val_acc: 0.9891
Epoch 66/100
392/392 [==============================] - 1s 2ms/step - loss: 0.0027 - acc: 0.9974 - val_loss: 0.0090 - val_acc: 0.9898
Epoch 67/100
392/392 [==============================] - 1s 2ms/step - loss: 0.0026 - acc: 0.9975 - val_loss: 0.0087 - val_acc: 0.9898
Epoch 68/100
392/392 [==============================] - 1s 2ms/step - loss:

In [19]:
#"""Change the name of model"""
#model.save('TrainingData_Linear_Regression_10_epochs.h5')

In [46]:
seq_len = 100
X_test_seq = X_test[:(X_test.shape[0] - X_test.shape[0] % seq_len),:]
shp = X_test_seq.shape
X_test_seq = np.reshape(X_test_seq, [shp[0]//seq_len, seq_len, shp[1]])
X_test_seq.shape

y_test_seq = y_train[:(X_test.shape[0] - X_test.shape[0] % seq_len)]
y_test_seq = np.reshape(y_test_seq, [shp[0]//seq_len, seq_len, 1])



In [47]:
result = model.evaluate(X_test_seq, y_test_seq, batch_size=48)
# print('Test score:', score)
# print('Test accuracy:', acc)
print("Loss: ", result)

187/187 [==============================] - 0s 866us/step
Loss:  [0.10911158201369373, 0.8871122984325185]


In [48]:
test_data = pd.read_csv('./syllabusCSCI4155CSCI6505.txt',sep=",", header=None, dtype="float").values
print(test_data.shape)

(1611, 79)


In [49]:
seq_len = 100
X_test_seq = X_test[:(X_test.shape[0] - X_test.shape[0] % seq_len),:]
shp = X_test_seq.shape
X_test_seq = np.reshape(X_test_seq, [shp[0]//seq_len, seq_len, shp[1]])
X_test_seq.shape

(187, 100, 79)

In [51]:
from sklearn.metrics import accuracy_score
prediction = np.where(model.predict(X_test_seq) > 0.5, 1, 0)

In [52]:
print(prediction)

[[[0]
  [0]
  [0]
  ...
  [0]
  [0]
  [0]]

 [[0]
  [0]
  [0]
  ...
  [0]
  [0]
  [0]]

 [[0]
  [0]
  [0]
  ...
  [0]
  [0]
  [0]]

 ...

 [[0]
  [0]
  [0]
  ...
  [0]
  [0]
  [0]]

 [[0]
  [0]
  [0]
  ...
  [0]
  [0]
  [0]]

 [[0]
  [0]
  [0]
  ...
  [0]
  [0]
  [0]]]


In [16]:
np.savetxt(r'syllabusCSCI4155CSCI6505_prediction.txt', prediction, fmt='%d')